const labels = {
    userMail: "Adres email",
    firstName: "Imię",
    lastName: "Nazwisko",
    dateBirth: "Data urodzenia",
    sex: "Płeć",
    address: "Adres korespondencyjny",
    phoneNumber: "Numer telefonu",
    insuranceType: "Typ ubezpieczenia",
    prescriptions: "Recepty",
    dateTo: "Data ważności",
    doctorMail: "Adres email lekarza",
    numberPWZ: "Numer prawa wykonywania zawodu",
    departmentNFZ: "Departament NFZ",
    permissions: "Dodatkowe uprawnienie",
    medicines: "Leki",
    medicalTests: "Badania",
    testDate: "Data badania",
    testName: "Nazwa badania",
    authorMail: "Adres email laboranta",
    parametersWithReference: "Wyniki z odniesieniem",
    fileId: "Dokument badania",
    referrals:"Skierowania",
    date: "Data",
    purpose: "Cel skierowania",
    recognition: "Rozpoznanie",
    treatments: "Historia chorób",
    numberICD: "Numer ICD",
    symptomsAndDiagnosis: "Objawy i diagnoza",
    information: "Opis",
    title:"Tytuł naukowy",
    prescriptionRefundNumber:"Numer pieczątki",
    pharmacotherapy: "Farmakoterapia",
    medicalAnalysisAndRecommendations: "Epikryza",
    pesel: "Pesel",
    specializations:"Specjalizacje"
}

export default labels;